-- PROGRESSION - 1


-- 1. **Create table city**
CREATE TABLE CITY 
( ID NUMBER(20),
NAME VARCHAR(50) NOT NULL,
CONSTRAINT CITY_PK PRIMARY KEY(ID));

INSERT INTO CITY(ID,NAME)VALUES(101,'TAMILNADU');

-- 2. **Create table referee**
CREATE TABLE REFREE
(ID NUMBER(20),
NAME VARCHAR(50) NOT NULL,
CONSTRAINT REFREE_PK PRIMARY KEY(ID));

INSERT INTO refree(ID,NAME)VALUES(102,'VENKY');
-- 3. **Create table innings**
CREATE TABLE INNINGS
(ID NUMBER(20),
INNINGS_NUMBER NUMBER(20) NOT NULL,
CONSTRAINT INNINGS_PK PRIMARY KEY(ID));

INSERT INTO INNINGS(ID,INNINGS_NUMBER)VALUES(103,20);


-- 4. **Create table extra_type**

CREATE TABLE EXTRA_TYPE
(ID NUMBER(20),
NAME VARCHAR(50) NOT NULL,
CONSTRAINT EXTRA_TYPE_PK PRIMARY KEY(ID));

INSERT INTO EXTRA_TYPE(ID,NAME)VALUES(104,'RAHUL');
-- 5. **Create table skill**
CREATE TABLE SKILL
(ID NUMBER(20),
NAME VARCHAR(50) NOT NULL,
CONSTRAINT SKILL_PK PRIMARY KEY(ID));

INSERT INTO SKILL(ID,NAME)VALUES(105,'GOODPLAYER');

-- 6. **Create table team**
CREATE TABLE TEAM
(ID NUMBER(20),
NAME VARCHAR(50) NOT NULL,
COACH VARCHAR(50) NOT NULL,
HOME_CITY NUMBER(20) NOT NULL,
CAPTAIN NUMBER(20) NOT NULL,
CONSTRAINT TEAM_PK PRIMARY KEY(ID),
CONSTRAINT FK_TEAM_HOME_CITY FOREIGN KEY(HOME_CITY) REFERENCES CITY(ID));


INSERT INTO TEAM(ID,NAME,COACH,HOME_CITY,CAPTAIN)VALUES(101,'TAMILNADU','JOHN',101,19);

-- 7. **Create table player**
CREATE TABLE PLAYER
(ID NUMBER(11),NAME VARCHAR(50)NOT NULL, COUNTRY VARCHAR(50) NOT NULL,
SKILL_ID NUMBER(11) NOT NULL, TEAM_ID NUMBER(11) NOT NULL,
CONSTRAINT FK_PLAYER_SKILL FOREIGN KEY (SKILL_ID) REFERENCES SKILL(ID),
CONSTRAINT FK_PLAYER_TEAM FOREIGN KEY (TEAM_ID) REFERENCES TEAM(ID));

INSERT INTO player(ID,NAME,country,skill_id,team_id)VALUES(109,'sachin','india',105,101);



-- 8. **Create table venue**
CREATE TABLE VENUE
(ID NUMBER(20),
STADIUM_NAME VARCHAR(50) NOT NULL,
CITY_ID NUMBER(20),
CONSTRAINT VENUE_PK PRIMARY KEY(ID),
CONSTRAINT VENUE_FK FOREIGN KEY(CITY_ID) REFERENCES CITY(ID));

INSERT INTO venue(ID,STADIUM_NAME,CITY_ID)VALUES(22,'CHEPAUK',101);

CREATE TABLE RAIDER

-- 9. **Create table event**
CREATE TABLE EVENT
(ID NUMBER(20),
INNINGS_ID NUMBER(20) NOT NULL,
EVENT_NO NUMBER(20) NOT NULL,
RAIDER_ID NUMBER(20)NOT NULL,
RAID_POINTS NUMBER(20) NOT NULL,
DEFENDING_POINTS NUMBER(20) NOT NULL,
CLOCK_IN_SECONDS NUMBER(20) NOT NULL,
TEAM_ONE_SCORE NUMBER(20)NOT NULL,
TEAM_TWO_SCORE NUMBER(20) NOT NULL,
CONSTRAINT EVENT_PK PRIMARY KEY(ID),
CONSTRAINT FK_EVENT_INNINGS_ID FOREIGN KEY(INNINGS_ID) REFERENCES INNINGS(ID),
CONSTRAINT FK_EVENT_RAIDER_ID FOREIGN KEY(RAIDER_ID) REFERENCES SKILL(ID));

INSERT INTO event(ID,INNINGS_ID,EVENT_NO,RAIDER_ID,RAID_POINTS,DEFENDING_POINTS,CLOCK_IN_SECONDS,TEAM_ONE_SCORE,TEAM_TWO_SCORE)VALUES(22,103,101,105,13,23,50,51,11);
-- 10. **Create table extra_event**
CREATE TABLE EXTRA_EVENT
(ID NUMBER(20),
EVENT_ID NUMBER(20) NOT NULL,
EXTRA_TYPE_ID NUMBER(10)NOT NULL,
POINTS NUMBER(20) NOT NULL,
SCORING_TEAM_ID NUMBER(20) NOT NULL,
CONSTRAINT EXTRA_EVENT_PK PRIMARY KEY(ID),
CONSTRAINT EXTRA_EVENT_EVENT_ID_FK FOREIGN KEY(EVENT_ID) REFERENCES EVENT(ID),
CONSTRAINT EXTRA_EVENT_EXTRA_TYPE_ID_FK FOREIGN KEY(EXTRA_TYPE_ID) REFERENCES EXTRA_TYPE(ID),
CONSTRAINT EXTRA_EVENT_SCORING_TEAM_ID_FK FOREIGN KEY(SCORING_TEAM_ID) REFERENCES TEAM(ID)
);

INSERT INTO EXTRA_EVENT(ID,EVENT_ID,EXTRA_TYPE_ID,POINTS,SCORING_TEAM_ID)VALUES(23,22,104,44,101);

-- 11. **Create table outcome**
CREATE TABLE OUTCOME
(
ID NUMBER(20) PRIMARY KEY,
STATUS VARCHAR(50) NOT NULL,
WINNER_TEAM_ID NUMBER(11),
SCORE NUMBER(11),
PLAYER_OF_MATCH NUMBER(11),

CONSTRAINT OUTCOME_WINNER_TEAM_FK FOREIGN KEY(WINNER_TEAM_ID) REFERENCES TEAM(ID),
CONSTRAINT KEY_OUTCOME_PLAYER_FK FOREIGN KEY(PLAYER_OF_MATCH) REFERENCES PLAYER(ID));

ALTER TABLE PLAYER ADD CONSTRAINT PLAYER_PK PRIMARY KEY(ID);

INSERT INTO OUTCOME(ID,STATUS,WINNER_TEAM_ID,SCORE,PLAYER_OF_MATCH)VALUES(11,'WIN',101,44,109);

-- 12. **Create table game**
CREATE TABLE GAMES(ID NUMBER(11),
GAME_DATE DATE,
TEAM_ID_1 NUMBER(11) NOT NULL,
TEAM_ID_2 NUMBER(11)NOT NULL,
VENUE_ID NUMBER(11) NOT NULL,
OUTCOME_ID NUMBER(11)NOT NULL, 
REFREE_ID_1 NUMBER(11)NOT NULL,  
REFREE_ID_2 NUMBER(11) NOT NULL,
FIRST_INNINGS_ID NUMBER(11) NOT NULL,SECOND_INNINGS_ID NUMBER(11) NOT NULL,
CONSTRAINT GAMES_PK PRIMARY KEY(ID),
CONSTRAINT GAMES_TEAM_FK FOREIGN KEY (TEAM_ID_1) REFERENCES TEAM(ID),
CONSTRAINT GAMES_TEAM1_FK FOREIGN KEY (TEAM_ID_2)REFERENCES TEAM(ID),
CONSTRAINT GAMES_VENUE_FK FOREIGN KEY (VENUE_ID)  REFERENCES VENUE(ID),
CONSTRAINT GAMES_OUTCOME_FK FOREIGN KEY  (OUTCOME_ID) REFERENCES  OUTCOME(ID),
CONSTRAINT GAMES_REFREE_FK  FOREIGN KEY   (REFREE_ID_1 )  REFERENCES  REFREE(ID),
CONSTRAINT GAMES_REFREE1_FK  FOREIGN KEY   (REFREE_ID_2)  REFERENCES  REFREE(ID),
CONSTRAINT GAMES_INNINGS_FK  FOREIGN  KEY (FIRST_INNINGS_ID ) REFERENCES   INNINGS(ID));

INSERT INTO GAMES(ID,GAME_DATE,TEAM_ID_1,TEAM_ID_2,VENUE_ID,OUTCOME_ID,REFREE_ID_1,REFREE_ID_2,FIRST_INNINGS_ID )VALUES(33,TO_DATE('07/07/2019','DD/MM/YYYY'),101,101,22,11,102,102,103);

UPDATE PLAYER SET NAME ='VENKI'
WHERE ID=109;

UPDATE PLAYER SET COUNTRY ='IND'
WHERE ID=109 AND NAME='VENKI';

DELETE FROM REFREE WHERE ID=102;
-- 13. **Drop table city**

-- 14. **Drop table innings**

-- 15. **Drop table skill**

-- 16. **Drop table extra_type**
COMMIT;


